[language-server.ruff]
command = "ruff"
args = ["server", "--preview"]

[[language]]
name = "python"
formatter = { command = "ruff", args = ["format"] }
language-servers = [ "pylsp", "ruff" ]

[[language]]
name = "latex"
file-types = ["tex","sty"]
comment-token = "%"

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
formatter = { command = "rustfmt" }
auto-format = true
